#!/usr/bin/env python3
"""
Cart-AJAX Cloner + Pagination/Infinite-Scroll Cloner
Clones Shopify cart drawer/modal logic + infinite scroll pagination.
"""
import re, sys, json
from pathlib import Path
from bs4 import BeautifulSoup

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 cart-pagination-cloner.py <extracted_dir>")
        sys.exit(1)
    
    extracted_dir = Path(sys.argv[1])
    print("=" * 60)
    print("Cart-AJAX + Pagination Cloner")
    print("=" * 60)
    
    cart_html_path = extracted_dir / "pages" / "cart.html"
    collection_html_path = extracted_dir / "pages" / "collection.html"
    
    # === CART AJAX ===
    print("\n--- Cart AJAX Cloner ---")
    
    # Detect cart type
    cart_type = "page"
    cart_soup = None
    if cart_html_path.exists():
        cart_soup = BeautifulSoup(cart_html_path.read_text(encoding='utf-8', errors='replace'), 'lxml')
        
        if cart_soup.find(class_=re.compile(r'cart.*drawer|drawer.*cart', re.I)):
            cart_type = "drawer"
        elif cart_soup.find(class_=re.compile(r'cart.*modal|modal.*cart', re.I)):
            cart_type = "modal"
        
        # Detect features
        has_qty_selector = bool(cart_soup.find(class_=re.compile(r'qty.*btn|quantity.*selector', re.I)))
        has_free_shipping = bool(cart_soup.find(class_=re.compile(r'free.*shipping|shipping.*progress|shipping.*bar', re.I)))
        has_discount_field = bool(cart_soup.find(attrs={'name': re.compile(r'discount|coupon', re.I)}))
        
        print(f"Cart type: {cart_type}")
        print(f"Quantity selector: {has_qty_selector}")
        print(f"Free shipping bar: {has_free_shipping}")
        print(f"Discount field: {has_discount_field}")
    
    # Generate cart drawer snippet
    snippets_dir = extracted_dir / "theme" / "snippets"
    snippets_dir.mkdir(parents=True, exist_ok=True)
    
    cart_drawer = """{%- comment -%}
  Cart Drawer - Auto-generated by cart-ajax-cloner
  Type: """ + cart_type + """
{%- endcomment -%}

<div class="cart-drawer" data-cart-drawer aria-hidden="true">
  <div class="cart-drawer__overlay" data-cart-overlay></div>
  <div class="cart-drawer__container" role="dialog" aria-label="{{ 'cart.general.title' | t }}" aria-modal="true">
    <div class="cart-drawer__header">
      <h2 class="cart-drawer__title">{{ 'cart.general.title' | t }}</h2>
      <button type="button" class="cart-drawer__close" data-cart-close aria-label="{{ 'cart.general.close' | t }}">
        &times;
      </button>
    </div>

    {%- if settings.free_shipping_bar -%}
      <div class="cart-drawer__shipping-bar" data-shipping-bar>
        <p class="shipping-bar__text" data-shipping-text></p>
        <div class="shipping-bar__progress">
          <div class="shipping-bar__fill" data-shipping-fill></div>
        </div>
      </div>
    {%- endif -%}

    <div class="cart-drawer__body" data-cart-body>
      <div class="cart-drawer__items" data-cart-items>
        {%- comment -%} Items rendered via JS {%- endcomment -%}
      </div>
    </div>

    <div class="cart-drawer__footer" data-cart-footer>
      <div class="cart-drawer__subtotal">
        <span class="cart-drawer__subtotal-label">{{ 'cart.general.subtotal' | t }}</span>
        <span class="cart-drawer__subtotal-value" data-cart-subtotal>{{ cart.total_price | money }}</span>
      </div>

      {%- if settings.cart_notes -%}
        <div class="cart-drawer__notes">
          <label for="CartNote">{{ 'cart.general.note' | t }}</label>
          <textarea id="CartNote" name="note" data-cart-note>{{ cart.note }}</textarea>
        </div>
      {%- endif -%}

      <p class="cart-drawer__taxes">
        {{ 'cart.general.taxes_and_shipping_at_checkout' | t }}
      </p>

      <button type="submit" name="checkout" class="btn btn--checkout" data-cart-checkout>
        {{ 'cart.general.checkout' | t }}
      </button>

      <a href="{{ routes.cart_url }}" class="cart-drawer__view-cart">
        {{ 'cart.general.view_cart' | t }}
      </a>
    </div>
  </div>
</div>
"""
    drawer_path = snippets_dir / "cart-drawer.liquid"
    drawer_path.write_text(cart_drawer, encoding='utf-8')
    print(f"{drawer_path} ({drawer_path.stat().st_size:,} bytes)")
    
    # Generate main-cart.liquid (cart page)
    sections_dir = extracted_dir / "theme" / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)
    
    cart_section = """{%- comment -%}
  Main Cart Section - Auto-generated
{%- endcomment -%}

<section class="cart-section" data-section-type="cart">
  <h1 class="cart__title">{{ 'cart.general.title' | t }}</h1>

  {%- if cart.item_count == 0 -%}
    <div class="cart__empty">
      <p>{{ 'cart.general.empty' | t }}</p>
      <a href="{{ routes.all_products_collection_url }}" class="btn">
        {{ 'cart.general.continue_shopping' | t }}
      </a>
    </div>
  {%- else -%}
    <form action="{{ routes.cart_url }}" method="post" class="cart__form" data-cart-form>
      <div class="cart__items">
        {%- for item in cart.items -%}
          <div class="cart__item" data-cart-item data-line="{{ forloop.index }}" data-variant-id="{{ item.variant_id }}">
            <div class="cart__item-image">
              {%- if item.image -%}
                <img src="{{ item.image | image_url: width: 150 }}"
                     alt="{{ item.title | escape }}"
                     loading="lazy"
                     width="150" height="150">
              {%- endif -%}
            </div>

            <div class="cart__item-info">
              <a href="{{ item.url }}" class="cart__item-title">{{ item.product.title }}</a>
              
              {%- if item.variant.title != 'Default Title' -%}
                <p class="cart__item-variant">{{ item.variant.title }}</p>
              {%- endif -%}

              {%- if item.selling_plan_allocation -%}
                <p class="cart__item-plan">{{ item.selling_plan_allocation.selling_plan.name }}</p>
              {%- endif -%}

              {%- if item.original_line_price != item.final_line_price -%}
                <p class="cart__item-price--compare">
                  <s>{{ item.original_line_price | money }}</s>
                </p>
              {%- endif -%}
              
              <p class="cart__item-price" data-item-price>
                {{ item.final_line_price | money }}
              </p>

              {%- for property in item.properties -%}
                {%- unless property.last == blank -%}
                  <p class="cart__item-property">
                    {{ property.first }}: {{ property.last }}
                  </p>
                {%- endunless -%}
              {%- endfor -%}
            </div>

            <div class="cart__item-quantity">
              <button type="button" class="qty-btn qty-btn--minus" data-qty-minus data-line="{{ forloop.index }}">&minus;</button>
              <input type="number"
                     name="updates[]"
                     value="{{ item.quantity }}"
                     min="0"
                     data-qty-input
                     data-line="{{ forloop.index }}"
                     aria-label="{{ 'cart.general.quantity' | t }}">
              <button type="button" class="qty-btn qty-btn--plus" data-qty-plus data-line="{{ forloop.index }}">&plus;</button>
            </div>

            <div class="cart__item-remove">
              <button type="button" class="cart__remove" data-cart-remove data-line="{{ forloop.index }}">
                {{ 'cart.general.remove' | t }}
              </button>
            </div>
          </div>
        {%- endfor -%}
      </div>

      <div class="cart__footer">
        <div class="cart__notes">
          <label for="CartNote">{{ 'cart.general.note' | t }}</label>
          <textarea id="CartNote" name="note" data-cart-note>{{ cart.note }}</textarea>
        </div>

        <div class="cart__summary">
          <div class="cart__subtotal">
            <span>{{ 'cart.general.subtotal' | t }}</span>
            <span data-cart-subtotal>{{ cart.total_price | money }}</span>
          </div>

          {%- if cart.cart_level_discount_applications.size > 0 -%}
            {%- for discount in cart.cart_level_discount_applications -%}
              <div class="cart__discount">
                <span>{{ discount.title }}</span>
                <span>-{{ discount.total_allocated_amount | money }}</span>
              </div>
            {%- endfor -%}
          {%- endif -%}

          <p class="cart__taxes">{{ 'cart.general.taxes_and_shipping_at_checkout' | t }}</p>

          <button type="submit" name="checkout" class="btn btn--checkout">
            {{ 'cart.general.checkout' | t }}
          </button>

          <a href="{{ routes.all_products_collection_url }}" class="cart__continue">
            {{ 'cart.general.continue_shopping' | t }}
          </a>
        </div>
      </div>
    </form>
  {%- endif -%}
</section>
"""
    cart_path = sections_dir / "main-cart.liquid"
    cart_path.write_text(cart_section, encoding='utf-8')
    print(f"{cart_path} ({cart_path.stat().st_size:,} bytes)")
    
    # Generate cart.js
    assets_dir = extracted_dir / "theme" / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    
    cart_js = """// cart.js - Auto-generated by cart-ajax-cloner
// Handles: add to cart, change quantity, remove item, update subtotal, drawer

class CartManager {
  constructor() {
    this.drawer = document.querySelector('[data-cart-drawer]');
    this.drawerBody = document.querySelector('[data-cart-items]');
    this.subtotalEl = document.querySelector('[data-cart-subtotal]');
    this.cartCountEls = document.querySelectorAll('[data-cart-count]');
    this.shippingBar = document.querySelector('[data-shipping-bar]');
    this.freeShippingThreshold = 10000; // $100 in cents
    
    this.bindEvents();
  }

  bindEvents() {
    // Add to cart
    document.addEventListener('submit', (e) => {
      if (e.target.matches('[data-product-form]')) {
        e.preventDefault();
        this.addToCart(new FormData(e.target));
      }
    });

    // Quantity buttons (delegated)
    document.addEventListener('click', (e) => {
      if (e.target.matches('[data-qty-plus]')) {
        const line = e.target.dataset.line;
        const input = document.querySelector(`[data-qty-input][data-line="${line}"]`);
        input.value = parseInt(input.value) + 1;
        this.changeItem(line, input.value);
      }
      if (e.target.matches('[data-qty-minus]')) {
        const line = e.target.dataset.line;
        const input = document.querySelector(`[data-qty-input][data-line="${line}"]`);
        const newVal = Math.max(0, parseInt(input.value) - 1);
        input.value = newVal;
        if (newVal === 0) {
          this.removeItem(line);
        } else {
          this.changeItem(line, newVal);
        }
      }
      if (e.target.matches('[data-cart-remove]')) {
        e.preventDefault();
        this.removeItem(e.target.dataset.line);
      }
      if (e.target.matches('[data-cart-close]') || e.target.matches('[data-cart-overlay]')) {
        this.closeDrawer();
      }
    });

    // Quantity input change
    document.addEventListener('change', (e) => {
      if (e.target.matches('[data-qty-input]')) {
        this.changeItem(e.target.dataset.line, e.target.value);
      }
      if (e.target.matches('[data-cart-note]')) {
        this.updateNote(e.target.value);
      }
    });

    // Escape to close
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') this.closeDrawer();
    });
  }

  async addToCart(formData) {
    try {
      const response = await fetch('/cart/add.js', {
        method: 'POST',
        body: formData
      });
      const data = await response.json();
      
      if (data.status === 422) {
        this.showError(data.description);
        return;
      }
      
      // Fetch updated cart
      await this.fetchCart();
      this.openDrawer();
      this.renderItems();
      this.updateCount();
    } catch (err) {
      console.error('Add to cart failed:', err);
    }
  }

  async changeItem(line, quantity) {
    try {
      const response = await fetch('/cart/change.js', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ line: parseInt(line), quantity: parseInt(quantity) })
      });
      const cart = await response.json();
      this.cart = cart;
      this.renderItems();
      this.updateCount();
      this.updateSubtotal();
      this.updateShippingBar();
    } catch (err) {
      console.error('Change item failed:', err);
    }
  }

  async removeItem(line) {
    await this.changeItem(line, 0);
  }

  async updateNote(note) {
    try {
      await fetch('/cart/update.js', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ note: note })
      });
    } catch (err) {
      console.error('Update note failed:', err);
    }
  }

  async fetchCart() {
    try {
      const response = await fetch('/cart.js');
      this.cart = await response.json();
    } catch (err) {
      console.error('Fetch cart failed:', err);
    }
  }

  renderItems() {
    if (!this.drawerBody) return;
    
    if (this.cart.item_count === 0) {
      this.drawerBody.innerHTML = '<p class="cart__empty">' + 
        (window.cartStrings?.empty || 'Your cart is empty') + '</p>';
      return;
    }

    this.drawerBody.innerHTML = this.cart.items.map((item, index) => `
      <div class="cart-drawer__item" data-line="${index + 1}">
        <div class="cart-drawer__item-image">
          ${item.image ? `<img src="${item.image}" alt="${item.title}" width="80" height="80" loading="lazy">` : ''}
        </div>
        <div class="cart-drawer__item-info">
          <a href="${item.url}" class="cart-drawer__item-title">${item.product_title}</a>
          ${item.variant_title ? `<p class="cart-drawer__item-variant">${item.variant_title}</p>` : ''}
          <p class="cart-drawer__item-price">${this.formatMoney(item.final_line_price)}</p>
        </div>
        <div class="cart-drawer__item-quantity">
          <button type="button" class="qty-btn qty-btn--minus" data-qty-minus data-line="${index + 1}">&minus;</button>
          <input type="number" value="${item.quantity}" min="0" data-qty-input data-line="${index + 1}"
                 aria-label="Quantity">
          <button type="button" class="qty-btn qty-btn--plus" data-qty-plus data-line="${index + 1}">&plus;</button>
        </div>
        <button type="button" class="cart-drawer__remove" data-cart-remove data-line="${index + 1}">
          Remove
        </button>
      </div>
    `).join('');
  }

  updateCount() {
    this.cartCountEls.forEach(el => {
      el.textContent = this.cart.item_count;
      el.style.display = this.cart.item_count > 0 ? '' : 'none';
    });
  }

  updateSubtotal() {
    if (this.subtotalEl) {
      this.subtotalEl.textContent = this.formatMoney(this.cart.total_price);
    }
  }

  updateShippingBar() {
    if (!this.shippingBar) return;
    
    const remaining = Math.max(0, this.freeShippingThreshold - this.cart.total_price);
    const pct = Math.min(100, (this.cart.total_price / this.freeShippingThreshold) * 100);
    
    const fill = document.querySelector('[data-shipping-fill]');
    const text = document.querySelector('[data-shipping-text]');
    
    if (fill) fill.style.width = pct + '%';
    
    if (text) {
      if (remaining > 0) {
        text.innerHTML = `You're <strong>${this.formatMoney(remaining)}</strong> away from free shipping!`;
      } else {
        text.innerHTML = 'You\'ve unlocked free shipping!';
      }
    }
  }

  openDrawer() {
    if (this.drawer) {
      this.drawer.classList.add('is-open');
      this.drawer.setAttribute('aria-hidden', 'false');
      document.body.style.overflow = 'hidden';
    }
  }

  closeDrawer() {
    if (this.drawer) {
      this.drawer.classList.remove('is-open');
      this.drawer.setAttribute('aria-hidden', 'true');
      document.body.style.overflow = '';
    }
  }

  formatMoney(cents) {
    const amount = (cents / 100).toFixed(2);
    if (window.Shopify && Shopify.currency) {
      return `${Shopify.currency.active} ${amount}`;
    }
    return `$${amount}`;
  }

  showError(msg) {
    // Simple error display
    alert(msg);
  }
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
  window.cartManager = new CartManager();
});
"""
    cart_js_path = assets_dir / "cart.js"
    cart_js_path.write_text(cart_js, encoding='utf-8')
    print(f"{cart_js_path} ({cart_js_path.stat().st_size:,} bytes)")
    
    # === PAGINATION / INFINITE SCROLL ===
    print("\n--- Pagination / Infinite Scroll ---")
    
    # Detect pagination type
    pagination_type = "standard"
    if collection_html_path.exists():
        col_soup = BeautifulSoup(collection_html_path.read_text(encoding='utf-8', errors='replace'), 'lxml')
        
        if col_soup.find(class_=re.compile(r'load.*more|show.*more', re.I)):
            pagination_type = "load-more"
        elif col_soup.find(class_=re.compile(r'infinite.*scroll|sentinel', re.I)):
            pagination_type = "infinite"
        elif col_soup.find(class_=re.compile(r'pagination|pager', re.I)):
            pagination_type = "standard"
        
        has_next_page = bool(col_soup.find(rel='next'))
        print(f"Pagination type: {pagination_type}")
        print(f"Next page detected: {has_next_page}")
    
    # Generate infinite-scroll.js
    infinite_js = """// infinite-scroll.js - Auto-generated
// Supports: standard pagination, load-more button, infinite scroll

class InfiniteScroll {
  constructor() {
    this.grid = document.querySelector('[data-product-grid]');
    this.pagination = document.querySelector('.pagination, [data-pagination]');
    this.loading = false;
    this.nextUrl = null;
    this.mode = '""" + pagination_type + """';
    
    if (!this.grid) return;
    
    this.findNextUrl();
    
    if (this.mode === 'infinite' && this.nextUrl) {
      this.setupInfiniteScroll();
    } else if (this.mode === 'load-more' && this.nextUrl) {
      this.setupLoadMore();
    }
  }

  findNextUrl() {
    const nextLink = document.querySelector('a[rel="next"]');
    if (nextLink) {
      this.nextUrl = nextLink.href;
    }
  }

  setupInfiniteScroll() {
    // Create sentinel element
    const sentinel = document.createElement('div');
    sentinel.className = 'infinite-scroll__sentinel';
    sentinel.setAttribute('data-sentinel', '');
    this.grid.parentNode.insertBefore(sentinel, this.grid.nextSibling);
    
    // Loading spinner
    const spinner = document.createElement('div');
    spinner.className = 'infinite-scroll__loading';
    spinner.innerHTML = '<div class="spinner"></div><p>Loading more products...</p>';
    spinner.style.display = 'none';
    sentinel.appendChild(spinner);
    
    // IntersectionObserver
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !this.loading && this.nextUrl) {
          this.loadMore(spinner);
        }
      });
    }, { rootMargin: '300px' });
    
    observer.observe(sentinel);
    this.observer = observer;
  }

  setupLoadMore() {
    const btn = document.createElement('button');
    btn.className = 'btn btn--load-more';
    btn.textContent = 'Load More';
    btn.setAttribute('data-load-more', '');
    
    btn.addEventListener('click', () => {
      if (!this.loading && this.nextUrl) {
        this.loadMore(null, btn);
      }
    });
    
    this.grid.parentNode.insertBefore(btn, this.grid.nextSibling);
  }

  async loadMore(spinner, btn) {
    this.loading = true;
    
    if (spinner) spinner.style.display = 'flex';
    if (btn) {
      btn.disabled = true;
      btn.textContent = 'Loading...';
    }
    
    try {
      const response = await fetch(this.nextUrl);
      const html = await response.text();
      const parser = new DOMParser();
      const doc = parser.parseFromString(html, 'text/html');
      
      const newItems = doc.querySelectorAll('[data-product-grid] > *');
      const newPagination = doc.querySelector('.pagination, [data-pagination]');
      
      // Append new items
      newItems.forEach(item => {
        this.grid.appendChild(item);
      });
      
      // Update next URL
      const newNext = doc.querySelector('a[rel="next"]');
      if (newNext) {
        this.nextUrl = newNext.href;
      } else {
        this.nextUrl = null;
        
        // No more pages
        if (this.observer) this.observer.disconnect();
        if (btn) {
          btn.textContent = 'No more products';
          btn.disabled = true;
        }
        if (spinner) spinner.style.display = 'none';
        
        // Show end message
        const endMsg = document.createElement('p');
        endMsg.className = 'infinite-scroll__end';
        endMsg.textContent = "You've reached the end!";
        this.grid.parentNode.insertBefore(endMsg, this.grid.nextSibling);
      }
      
      // Update URL
      window.history.pushState({}, '', this.nextUrl || window.location.href);
      
    } catch (err) {
      console.error('Load more failed:', err);
    } finally {
      this.loading = false;
      if (spinner) spinner.style.display = 'none';
      if (btn && this.nextUrl) {
        btn.disabled = false;
        btn.textContent = 'Load More';
      }
    }
  }
}

document.addEventListener('DOMContentLoaded', () => {
  new InfiniteScroll();
});
"""
    infinite_js_path = assets_dir / "infinite-scroll.js"
    infinite_js_path.write_text(infinite_js, encoding='utf-8')
    print(f"{infinite_js_path} ({infinite_js_path.stat().st_size:,} bytes)")
    
    print(f"\n{'='*60}")
    print("Cart-AJAX + Pagination Cloner Complete!")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
