#!/usr/bin/env python3
"""
CSS INJECTOR - Inject Extracted Styles into Shopify Liquid Theme
Takes theme.css + animations.css from extraction, injects into theme layout
Part of Shopify Recon | 2026-06-21

Usage: python3 css-injector.py <theme-dir> <css-dir> [output-dir]
Example: python3 css-injector.py ./theme ./extracted-styles ./theme-styled
"""

import json
import sys
import os
import re
from datetime import datetime


def inject_css_into_layout(theme_dir, theme_css, animations_css, output_dir):
    """Inject CSS into theme.liquid layout"""
    
    # Read theme.liquid
    layout_path = os.path.join(theme_dir, "layout", "theme.liquid")
    if not os.path.exists(layout_path):
        print(f"No layout/theme.liquid found in {theme_dir}")
        return False
    
    with open(layout_path) as f:
        layout = f.read()
    
    # Build injected CSS block
    injected_css = f"""
<!-- ═══ Injected by Shopify Recon CSS Injector ═══ -->
<style>
/* Theme CSS - Extracted from competitor store */
{theme_css}

/* Animation CSS - Extracted hover effects, transitions, keyframes */
{animations_css}
</style>
<!-- ═══ End Injected CSS ═══ -->
"""
    
    # Find {{ content_for_header }} and inject after it
    if "{{ content_for_header }}" in layout:
        layout = layout.replace(
            "{{ content_for_header }}",
            "{{ content_for_header }}\n" + injected_css
        )
        print("  CSS injected after content_for_header")
    elif "</head>" in layout:
        layout = layout.replace("</head>", injected_css + "\n</head>")
        print("  CSS injected before </head>")
    else:
        # Fallback: inject at the beginning
        layout = injected_css + "\n" + layout
        print("   CSS injected at beginning (no head tag found)")
    
    # Also add CSS asset references for production use
    asset_ref = """
<!-- CSS asset references (for production deployment) -->
<link rel="stylesheet" href="{{ 'theme.css' | asset_url }}">
<link rel="stylesheet" href="{{ 'animations.css' | asset_url }}">
"""
    
    if "{{ 'theme.css' | asset_url }}" not in layout:
        if "</head>" in layout:
            layout = layout.replace("</head>", asset_ref + "\n</head>")
    
    # Write output
    os.makedirs(os.path.join(output_dir, "layout"), exist_ok=True)
    output_layout = os.path.join(output_dir, "layout", "theme.liquid")
    with open(output_layout, "w") as f:
        f.write(layout)
    
    return True


def inject_inline_styles_to_templates(theme_dir, css_data, output_dir):
    """Inject component-specific styles into each template"""
    
    templates_dir = os.path.join(theme_dir, "templates")
    if not os.path.exists(templates_dir):
        return
    
    output_templates = os.path.join(output_dir, "templates")
    os.makedirs(output_templates, exist_ok=True)
    
    # Copy all template files
    for root, dirs, files in os.walk(templates_dir):
        for f in files:
            src = os.path.join(root, f)
            rel_path = os.path.relpath(src, templates_dir)
            dst = os.path.join(output_templates, rel_path)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            
            with open(src) as fh:
                content = fh.read()
            
            # Add template-specific CSS class to body
            template_name = os.path.splitext(f)[0]
            
            with open(dst, "w") as fh:
                fh.write(content)


def create_asset_files(css_data, output_dir):
    """Create theme.css and animations.css as Shopify assets"""
    assets_dir = os.path.join(output_dir, "assets")
    os.makedirs(assets_dir, exist_ok=True)
    
    # theme.css
    if css_data.get("theme_css"):
        with open(os.path.join(assets_dir, "theme.css"), "w") as f:
            f.write(css_data["theme_css"])
        print("  assets/theme.css created")
    
    # animations.css
    if css_data.get("animations_css"):
        with open(os.path.join(assets_dir, "animations.css"), "w") as f:
            f.write(css_data["animations_css"])
        print("  assets/animations.css created")
    
    # Create a base theme.js for interactions
    theme_js = """// theme.js - Generated by Shopify Recon
document.addEventListener('DOMContentLoaded', function() {
  
  // ===== Cart drawer toggle =====
  var cartToggle = document.querySelector('[data-cart-toggle], .cart-toggle, .header-cart');
  if (cartToggle) {
    cartToggle.addEventListener('click', function(e) {
      e.preventDefault();
      var drawer = document.querySelector('.cart-drawer, #CartDrawer');
      if (drawer) drawer.classList.toggle('open');
    });
  }
  
  // ===== Mobile menu toggle =====
  var menuToggle = document.querySelector('[data-menu-toggle], .menu-toggle, .hamburger');
  if (menuToggle) {
    menuToggle.addEventListener('click', function() {
      var menu = document.querySelector('.mobile-menu, #MobileMenu');
      if (menu) menu.classList.toggle('open');
    });
  }
  
  // ===== Product image gallery =====
  var thumbnails = document.querySelectorAll('.product-thumbnails .thumbnail, [data-image-id]');
  thumbnails.forEach(function(thumb) {
    thumb.addEventListener('click', function() {
      var newSrc = this.getAttribute('data-image-src') || this.querySelector('img').src;
      var mainImage = document.getElementById('ProductMainImage') || document.querySelector('.product-main-image img');
      if (mainImage && newSrc) mainImage.src = newSrc;
    });
  });
  
  // ===== Quantity selector =====
  var qtyButtons = document.querySelectorAll('[onclick*="updateQty"]');
  qtyButtons.forEach(function(btn) {
    btn.addEventListener('click', function() {
      // Already handled by inline onclick
    });
  });
  
  // ===== Filter toggle on mobile =====
  var filterToggle = document.querySelector('.filter-toggle, [onclick*="toggleFilters"]');
  if (filterToggle) {
    filterToggle.addEventListener('click', function() {
      var panel = document.getElementById('FilterPanel') || document.querySelector('.filter-panel');
      if (panel) panel.classList.toggle('open');
    });
  }
  
  // ===== Smooth scroll for anchor links =====
  document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
    anchor.addEventListener('click', function(e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
  
  // ===== Intersection Observer for scroll animations =====
  if ('IntersectionObserver' in window) {
    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('in-view', 'animated');
        }
      });
    }, { threshold: 0.1, rootMargin: '0px 0px -50px 0px' });
    
    // Observe elements with animation classes
    document.querySelectorAll('[data-aos], .fade-in, .slide-up, .zoom-in').forEach(function(el) {
      observer.observe(el);
    });
  }
  
  // ===== Sticky header =====
  var header = document.querySelector('.site-header, header');
  if (header) {
    var lastScroll = 0;
    window.addEventListener('scroll', function() {
      var currentScroll = window.pageYOffset;
      if (currentScroll > 100) {
        header.classList.add('sticky', 'scrolled');
      } else {
        header.classList.remove('sticky', 'scrolled');
      }
      lastScroll = currentScroll;
    });
  }
  
  // ===== AJAX cart update =====
  window.updateCartDrawer = function() {
    fetch('/cart.js')
      .then(function(r) { return r.json(); })
      .then(function(cart) {
        var countEl = document.querySelector('.cart-count');
        if (countEl) countEl.textContent = cart.item_count;
        
        var subtotalEl = document.querySelector('.cart-subtotal .value');
        if (subtotalEl) {
          subtotalEl.textContent = '$' + (cart.total_price / 100).toFixed(2);
        }
      });
  };
  
  // ===== Add to cart AJAX =====
  var addToCartForms = document.querySelectorAll('#AddToCartForm, form[action="/cart/add"]');
  addToCartForms.forEach(function(form) {
    form.addEventListener('submit', function(e) {
      e.preventDefault();
      var formData = new FormData(form);
      
      fetch('/cart/add.js', {
        method: 'POST',
        body: formData
      })
      .then(function(r) { return r.json(); })
      .then(function(data) {
        // Open cart drawer
        var drawer = document.querySelector('.cart-drawer, #CartDrawer');
        if (drawer) drawer.classList.add('open');
        window.updateCartDrawer();
        
        // Show success message
        var msg = document.createElement('div');
        msg.className = 'cart-success-message';
        msg.textContent = 'Added to cart!';
        msg.style.cssText = 'position:fixed;top:20px;right:20px;background:#4CAF50;color:white;padding:1rem;border-radius:4px;z-index:9999;';
        document.body.appendChild(msg);
        setTimeout(function() { msg.remove(); }, 3000);
      })
      .catch(function(err) {
        console.error('Add to cart error:', err);
      });
    });
  });
});
"""
    with open(os.path.join(assets_dir, "theme.js"), "w") as f:
        f.write(theme_js)
    print("  assets/theme.js created (interactions)")


def copy_theme_structure(theme_dir, output_dir):
    """Copy entire theme structure to output"""
    import shutil
    
    # Copy everything first
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    shutil.copytree(theme_dir, output_dir)
    print(f"  Theme structure copied to {output_dir}")


def main():
    if len(sys.argv) < 3:
        print("CSS INJECTOR")
        print("━" * 69)
        print()
        print("Usage: python3 css-injector.py <theme-dir> <styles-dir> [output-dir]")
        print("Example: python3 css-injector.py ./theme ./styles ./theme-styled")
        sys.exit(1)
    
    theme_dir = sys.argv[1]
    styles_dir = sys.argv[2]
    output_dir = sys.argv[3] if len(sys.argv) > 3 else theme_dir + "-styled"
    
    print("CSS INJECTOR")
    print("━" * 69)
    print(f"  Theme: {theme_dir}")
    print(f"  Styles: {styles_dir}")
    print(f"  Output: {output_dir}")
    print()
    
    # Load CSS files
    css_data = {}
    
    # Theme CSS
    theme_css_path = os.path.join(styles_dir, "theme.css")
    if os.path.exists(theme_css_path):
        with open(theme_css_path) as f:
            css_data["theme_css"] = f.read()
        print(f"  theme.css loaded: {len(css_data['theme_css'])} bytes")
    else:
        css_data["theme_css"] = ""
        print("   No theme.css found")
    
    # Animations CSS
    anim_css_path = None
    # Try multiple locations
    for path in [
        os.path.join(styles_dir, "animations.css"),
        os.path.join(styles_dir, "animations", "animations.css"),
        os.path.join(os.path.dirname(styles_dir), "animations", "animations.css"),
    ]:
        if os.path.exists(path):
            anim_css_path = path
            break
    
    if anim_css_path:
        with open(anim_css_path) as f:
            css_data["animations_css"] = f.read()
        print(f"  animations.css loaded: {len(css_data['animations_css'])} bytes")
    else:
        css_data["animations_css"] = ""
        print("   No animations.css found")
    
    if not css_data["theme_css"] and not css_data["animations_css"]:
        print("\nNo CSS files found to inject!")
        sys.exit(1)
    
    # Step 1: Copy theme structure
    print("\n  [1/3] Copying theme structure...")
    copy_theme_structure(theme_dir, output_dir)
    
    # Step 2: Inject CSS into layout
    print("\n  [2/3] Injecting CSS into theme.liquid...")
    inject_css_into_layout(output_dir, css_data["theme_css"], css_data["animations_css"], output_dir)
    
    # Step 3: Create asset files
    print("\n  [3/3] Creating asset files...")
    create_asset_files(css_data, output_dir)
    
    # Summary
    print(f"\nCSS INJECTION COMPLETE")
    print(f"━" * 69)
    print(f"  Output: {output_dir}/")
    print(f"  layout/theme.liquid - CSS injected inline + asset refs")
    print(f"  assets/theme.css - Competitor design system")
    print(f"  assets/animations.css - Hover effects, transitions, keyframes")
    print(f"  assets/theme.js - Cart, menu, gallery, scroll interactions")
    print()
    print(f"Deploy:")
    print(f"  shopify theme dev --store=YOUR_STORE.myshopify.com --path={output_dir}")
    print(f"  shopify theme push --store=YOUR_STORE.myshopify.com --path={output_dir}")


if __name__ == "__main__":
    main()
