#!/bin/bash
# SHOPIFY LIQUID INSPECTOR - Quick Start
# Copy-paste commands untuk mulai analyze Shopify stores

echo "SHOPIFY LIQUID INSPECTOR QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TOOL LOCATION:"
echo "   /home/ubuntu/tools/shopify-liquid-inspector.sh"
echo ""
echo "DOCUMENTATION:"
echo "   /home/ubuntu/tools/SHOPIFY-LIQUID-TOOLS-GUIDE.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BASIC USAGE:"
echo ""
echo "1. Extract a Shopify store:"
echo "   /home/ubuntu/tools/shopify-liquid-inspector.sh https://www.store.com ./output"
echo ""
echo "2. View theme metadata:"
echo "   jq . ./output/theme-metadata.json"
echo ""
echo "3. Count products:"
echo "   jq '.products | length' ./output/api/products.json"
echo ""
echo "4. Read full analysis:"
echo "   cat ./output/LIQUID-ANALYSIS.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "EXAMPLE STORES TO TRY:"
echo "   https://www.allbirds.com"
echo "   https://rothys.com"
echo "   https://www.taylorstitch.com"
echo "   https://gymshark.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "WHAT YOU GET:"
echo "   Product catalog (250+ products)"
echo "   Collections structure"
echo "   Theme metadata & ID"
echo "   HTML homepage for inspection"
echo "   Theme assets (CSS/JS URLs)"
echo "   Full analysis report"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
