#!/usr/bin/env python3
"""
FULL TEMPLATE GENERATOR - Generate Complete Shopify Theme Templates
Creates: product, collection, search, cart, 404, page, blog, list-collections
Part of Shopify Recon | 2026-06-21

Usage: python3 template-generator.py <page-analysis.json> <output-dir>
Example: python3 template-generator.py ./page-analysis.json ./my-theme
"""

import json
import sys
import os
from datetime import datetime


def load_analysis(path):
    with open(path) as f:
        return json.load(f)


def generate_product_template(page_data):
    """Generate product.liquid based on extracted product page data"""
    pd = page_data.get("product_data", {})
    
    has_atc = pd.get("has_add_to_cart_form", True)
    has_breadcrumbs = pd.get("has_breadcrumbs", True)
    has_reviews = pd.get("has_reviews", True)
    has_related = pd.get("has_related_products", True)
    has_size_chart = pd.get("has_size_chart", False)
    has_dynamic = pd.get("has_dynamic_checkout", False)
    
    template = '''<!-- product.liquid - Generated by Shopify Recon -->
<div class="product-page" itemscope itemtype="http://schema.org/Product">
  
  {% if collection %}
    <nav class="breadcrumbs" aria-label="breadcrumbs">
      <a href="{{ shop.url }}">Home</a>
      <span aria-hidden="true">/</span>
      <a href="{{ collection.url }}">{{ collection.title }}</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">{{ product.title }}</span>
    </nav>
  {% endif %}

  <div class="product-layout">
    <!-- Image Gallery -->
    <div class="product-gallery">
      {% if product.featured_image %}
        <div class="product-main-image">
          <img src="{{ product.featured_image | image_url: width: 800 }}"
               alt="{{ product.title | escape }}"
               id="ProductMainImage"
               width="800" height="800"
               loading="eager">
        </div>
      {% endif %}
      
      {% if product.images.size > 1 %}
        <div class="product-thumbnails">
          {% for image in product.images limit: 6 %}
            <button class="thumbnail" data-image-id="{{ image.id }}"
                    onclick="swapMainImage('{{ image | image_url: width: 800 }}')">
              <img src="{{ image | image_url: width: 150 }}" 
                   alt="{{ product.title | escape }}"
                   loading="lazy"
                   width="150" height="150">
            </button>
          {% endfor %}
        </div>
      {% endif %}
    </div>

    <!-- Product Info -->
    <div class="product-info">
      <h1 itemprop="name">{{ product.title }}</h1>
      
      <div class="product-price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
        <meta itemprop="priceCurrency" content="{{ cart.currency.iso_code }}">
        <meta itemprop="price" content="{{ product.price | money_without_currency }}">
        <link itemprop="availability" 
              href="http://schema.org/{% if product.available %}InStock{% else %}OutOfStock{% endif %}">
        
        <span class="price-current">{{ product.price | money }}</span>
        {% if product.compare_at_price > product.price %}
          <span class="price-compare">{{ product.compare_at_price | money }}</span>
          <span class="price-sale">Sale</span>
        {% endif %}
      </div>
      
      <div class="product-description rte" itemprop="description">
        {{ product.description }}
      </div>
      
      {% if has_size_chart %}
        <div class="size-chart-link">
          <button onclick="toggleSizeChart()">Size Guide</button>
          <div id="SizeChart" style="display:none;">
            {% if product.metafields.custom.size_chart %}
              {{ product.metafields.custom.size_chart }}
            {% else %}
              {{ pages.size-chart.content }}
            {% endif %}
          </div>
        </div>
      {% endif %}
      
      <!-- Add to Cart Form -->
      {% if has_atc %}
        <form action="/cart/add" method="post" enctype="multipart/form-data" 
              id="AddToCartForm" class="product-form">
          
          {% unless product.has_only_default_variant %}
            {% for option in product.options_with_values %}
              <div class="product-option">
                <label for="Option{{ option.position }}">{{ option.name }}</label>
                <select id="Option{{ option.position }}" 
                        name="options[{{ option.name | escape }}]"
                        onchange="onVariantChange()">
                  {% for value in option.values %}
                    <option value="{{ value | escape }}" 
                            {% if option.selected_value == value %}selected{% endif %}>
                      {{ value }}
                    </option>
                  {% endfor %}
                </select>
              </div>
            {% endfor %}
          {% endunless %}
          
          <div class="product-quantity">
            <label for="Quantity">Quantity</label>
            <input type="number" id="Quantity" name="quantity" value="1" min="1" max="99">
          </div>
          
          <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}">
          
          <button type="submit" name="add" 
                  class="btn btn-add-to-cart"
                  {% unless product.available %}disabled{% endunless %}>
            {% if product.available %}
              Add to Cart
            {% else %}
              Sold Out
            {% endif %}
          </button>
        </form>
      {% endif %}
      
      <!-- Dynamic Checkout Button -->
      {% if has_dynamic %}
        {{ form | payment_button }}
      {% endif %}
      
      <!-- Product Meta -->
      <div class="product-meta">
        {% if product.type %}
          <p class="product-type">Type: {{ product.type | link_to_type }}</p>
        {% endif %}
        {% if product.vendor %}
          <p class="product-vendor">Vendor: {{ product.vendor | link_to_vendor }}</p>
        {% endif %}
        <p class="product-sku">SKU: {{ product.selected_or_first_available_variant.sku }}</p>
      </div>
    </div>
  </div>

  <!-- Reviews Section -->
  {% if has_reviews %}
    <div class="product-reviews" id="reviews">
      <h2>Customer Reviews</h2>
      <div id="shopify-product-reviews" data-id="{{ product.id }}">
        {{ product.metafields.reviews }}
      </div>
    </div>
  {% endif %}

  <!-- Related Products -->
  {% if has_related %}
    <div class="related-products">
      <h2>You May Also Like</h2>
      <div class="product-grid">
        {% for product in product.collections.first.products limit: 4 %}
          {% unless product.id == product.id %}
            {% render 'product-card', product: product %}
          {% endunless %}
        {% endfor %}
      </div>
    </div>
  {% endif %}
</div>

<script>
  function swapMainImage(url) {
    document.getElementById('ProductMainImage').src = url;
  }
  function toggleSizeChart() {
    var chart = document.getElementById('SizeChart');
    chart.style.display = chart.style.display === 'none' ? 'block' : 'none';
  }
  function onVariantChange() {
    // Update variant ID and price on selection change
    var form = document.getElementById('AddToCartForm');
    // Shopify's URL variant selection
    var selectedOptions = Array.from(form.querySelectorAll('select')).map(s => s.value);
    var variant = productVariants.find(v => 
      selectedOptions.every((opt, i) => v.options[i] === opt)
    );
    if (variant) {
      form.querySelector('input[name="id"]').value = variant.id;
      document.querySelector('.price-current').textContent = formatMoney(variant.price);
    }
  }
</script>
'''
    return template


def generate_collection_template(page_data):
    """Generate collection.liquid based on extracted collection page data"""
    cd = page_data.get("collection_data", {})
    
    filter_types = cd.get("filter_types", [])
    has_sort = cd.get("has_sort", True)
    has_pagination = cd.get("has_pagination", True)
    layout = cd.get("layout", "grid")
    
    template = '''<!-- collection.liquid - Generated by Shopify Recon -->
<div class="collection-page">
  
  <header class="collection-header">
    <h1>{{ collection.title }}</h1>
    
    {% if collection.description != blank %}
      <div class="collection-description rte">
        {{ collection.description }}
      </div>
    {% endif %}
  </header>

  <div class="collection-toolbar">
    <!-- Filters -->
    {% if collection.filters.size > 0 %}
      <div class="collection-filters">
        <button class="filter-toggle" onclick="toggleFilters()">Filters</button>
        <div class="filter-panel" id="FilterPanel">
          {% for filter in collection.filters %}
            <div class="filter-group">
              <h3>{{ filter.label }}</h3>
              {% for value in filter.values %}
                <label class="filter-option">
                  <input type="checkbox" 
                         name="{{ filter.param_name }}"
                         value="{{ value.value }}"
                         {% if value.active %}checked{% endif %}
                         {% if value.count == 0 and value.active == false %}disabled{% endif %}>
                  <span>{{ value.label }} ({{ value.count }})</span>
                </label>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    
    <!-- Sort -->
    {% if has_sort %}
      <div class="collection-sort">
        <label for="SortBy">Sort by:</label>
        <select id="SortBy" onchange="onSortChange()">
          <option value="manual">Featured</option>
          <option value="best-selling">Best Selling</option>
          <option value="title-ascending">Alphabetically, A-Z</option>
          <option value="title-descending">Alphabetically, Z-A</option>
          <option value="price-ascending">Price, low to high</option>
          <option value="price-descending">Price, high to low</option>
          <option value="created-descending">Date, new to old</option>
          <option value="created-ascending">Date, old to new</option>
        </select>
      </div>
    {% endif %}
  </div>

  <!-- Product Grid -->
  <div class="product-grid {{ layout }}">
    {% for product in collection.products %}
      {% render 'product-card', product: product %}
    {% else %}
      <p class="no-products">No products found in this collection.</p>
    {% endfor %}
  </div>

  <!-- Pagination -->
  {% if has_pagination %}
    {% if paginate.pages > 1 %}
      <nav class="pagination" aria-label="Pagination">
        {% if paginate.previous %}
          <a href="{{ paginate.previous.url }}" class="prev">&laquo; Previous</a>
        {% endif %}
        
        {% for part in paginate.parts %}
          {% if part.is_link %}
            <a href="{{ part.url }}">{{ part.title }}</a>
          {% else %}
            {% if part.title == paginate.current_page %}
              <span class="current" aria-current="page">{{ part.title }}</span>
            {% else %}
              <span>{{ part.title }}</span>
            {% endif %}
          {% endif %}
        {% endfor %}
        
        {% if paginate.next %}
          <a href="{{ paginate.next.url }}" class="next">Next &raquo;</a>
        {% endif %}
      </nav>
    {% endif %}
  {% endif %}
</div>

<script>
  function toggleFilters() {
    var panel = document.getElementById('FilterPanel');
    panel.classList.toggle('open');
  }
  function onSortChange() {
    var sort = document.getElementById('SortBy').value;
    var url = new URL(window.location);
    url.searchParams.set('sort_by', sort);
    window.location = url;
  }
</script>
'''
    return template


def generate_search_template(page_data):
    """Generate search.liquid based on extracted search page data"""
    sd = page_data.get("search_data", {})
    
    has_predictive = sd.get("has_predictive_search", True)
    
    template = '''<!-- search.liquid - Generated by Shopify Recon -->
<div class="search-page">
  
  <h1>Search</h1>
  
  <form action="/search" method="get" role="search" class="search-form">
    <input type="search" 
           name="q" 
           value="{{ search.terms | escape }}"
           placeholder="Search products..."
           class="search-input"
           {% if has_predictive %}data-predictive-search{% endif %}>
    
    <select name="type" class="search-type">
      <option value="product" {% if search.types contains 'product' %}selected{% endif %}>Products</option>
      <option value="article" {% if search.types contains 'article' %}selected{% endif %}>Articles</option>
      <option value="page" {% if search.types contains 'page' %}selected{% endif %}>Pages</option>
    </select>
    
    <button type="submit" class="btn btn-search">Search</button>
  </form>

  {% if search.performed %}
    {% if search.results.size > 0 %}
      <p class="search-results-count">
        {{ search.results_count }} result{{ search.results_count | pluralize }} for "{{ search.terms }}"
      </p>
      
      <div class="search-results">
        {% for item in search.results %}
          {% if item.object_type == 'product' %}
            <div class="search-result product-result">
              {% render 'product-card', product: item %}
            </div>
          {% elsif item.object_type == 'article' %}
            <div class="search-result article-result">
              <a href="{{ item.url }}">
                <h3>{{ item.title }}</h3>
                <p>{{ item.content | strip_html | truncatewords: 30 }}</p>
              </a>
            </div>
          {% elsif item.object_type == 'page' %}
            <div class="search-result page-result">
              <a href="{{ item.url }}">
                <h3>{{ item.title }}</h3>
                <p>{{ item.content | strip_html | truncatewords: 30 }}</p>
              </a>
            </div>
          {% endif %}
        {% endfor %}
      </div>
      
      {% if paginate.pages > 1 %}
        <nav class="pagination">
          {% if paginate.previous %}
            <a href="{{ paginate.previous.url }}">&laquo; Previous</a>
          {% endif %}
          {% for part in paginate.parts %}
            {% if part.is_link %}
              <a href="{{ part.url }}">{{ part.title }}</a>
            {% else %}
              <span class="current">{{ part.title }}</span>
            {% endif %}
          {% endfor %}
          {% if paginate.next %}
            <a href="{{ paginate.next.url }}">Next &raquo;</a>
          {% endif %}
        </nav>
      {% endif %}
      
    {% else %}
      <div class="search-no-results">
        <p>No results found for "{{ search.terms }}".</p>
        <p>Try different keywords or check spelling.</p>
        
        <h3>Popular Searches</h3>
        <div class="popular-searches">
          <a href="/search?q=new+arrivals">New Arrivals</a>
          <a href="/search?q=best+sellers">Best Sellers</a>
          <a href="/search?q=sale">Sale</a>
        </div>
      </div>
    {% endif %}
  {% endif %}
</div>

{% if has_predictive %}
<script>
  // Predictive search
  var searchInput = document.querySelector('[data-predictive-search]');
  if (searchInput) {
    var debounceTimer;
    searchInput.addEventListener('input', function() {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(function() {
        var query = searchInput.value;
        if (query.length < 2) return;
        
        fetch('/search/suggest.json?q=' + encodeURIComponent(query) + '&resources[type]=product')
          .then(r => r.json())
          .then(data => {
            var products = data.resources.results.products || [];
            showSearchSuggestions(products);
          })
          .catch(err => console.error('Search error:', err));
      }, 300);
    });
  }
  
  function showSearchSuggestions(products) {
    var existing = document.getElementById('SearchSuggestions');
    if (existing) existing.remove();
    
    if (products.length === 0) return;
    
    var div = document.createElement('div');
    div.id = 'SearchSuggestions';
    div.className = 'search-suggestions';
    
    products.slice(0, 5).forEach(function(p) {
      var a = document.createElement('a');
      a.href = '/products/' + p.handle;
      a.innerHTML = '<img src="' + p.image + '" alt="' + p.title + '" width="50">' +
                     '<span>' + p.title + '</span>' +
                     '<span class="price">' + p.price + '</span>';
      div.appendChild(a);
    });
    
    searchInput.parentNode.appendChild(div);
  }
</script>
{% endif %}
'''
    return template


def generate_cart_template(page_data):
    """Generate cart.liquid based on extracted cart page data"""
    cd = page_data.get("cart_data", {})
    
    has_qty = cd.get("has_quantity_selector", True)
    has_remove = cd.get("has_remove_button", True)
    has_notes = cd.get("has_cart_note", True)
    has_discount = cd.get("has_discount_field", False)
    has_checkout = cd.get("has_checkout_button", True)
    has_empty_msg = cd.get("has_empty_message", True)
    
    # Build cart template without f-string to avoid Liquid {%%} conflicts
    qty_section = ""
    if has_qty:
        qty_section = '''            <div class="cart-item-quantity">
              <button type="button" onclick="updateQty({{ forloop.index }}, -1)">-</button>
              <input type="number" name="updates[]" value="{{ item.quantity }}" min="0"
                     onchange="updateQty({{ forloop.index }}, this.value)">
              <button type="button" onclick="updateQty({{ forloop.index }}, 1)">+</button>
            </div>'''
    
    remove_section = ""
    if has_remove:
        remove_section = '''            <div class="cart-item-remove">
              <a href="/cart/change?line={{ forloop.index }}&quantity=0"
                 class="remove-link">Remove</a>
            </div>'''
    
    notes_section = ""
    if has_notes:
        notes_section = '''        <div class="cart-note">
          <label for="CartNote">Order Note</label>
          <textarea name="note" id="CartNote" placeholder="Special instructions...">
            {{ cart.note }}
          </textarea>
        </div>'''
    
    discount_section = ""
    if has_discount:
        discount_section = '''        <div class="cart-discount">
          <label for="CartDiscount">Discount Code</label>
          <input type="text" id="CartDiscount" placeholder="Enter code">
          <button type="button" onclick="applyDiscount()">Apply</button>
        </div>'''
    
    checkout_section = ""
    if has_checkout:
        checkout_section = '''        <div class="cart-actions">
          <a href="/collections/all" class="btn btn-continue">Continue Shopping</a>
          <button type="submit" name="checkout" class="btn btn-checkout">
            Checkout • {{ cart.total_price | money }}
          </button>
        </div>'''
    
    empty_section = ""
    if has_empty_msg:
        empty_section = '''    <div class="cart-empty">
      <h2>Your cart is empty</h2>
      <p>Looks like you haven't added anything yet.</p>
      <a href="/collections/all" class="btn btn-shop">Start Shopping</a>
    </div>'''
    
    template = '''<!-- cart.liquid - Generated by Shopify Recon -->
<div class="cart-page">
  
  <h1>Shopping Cart</h1>
  
  {% if cart.item_count > 0 %}
    
    <form action="/cart" method="post" class="cart-form">
      
      <div class="cart-items">
        {% for item in cart.items %}
          <div class="cart-item" data-line="{{ forloop.index }}">
            <div class="cart-item-image">
              <a href="{{ item.url }}">
                {% if item.image %}
                  <img src="{{ item.image | image_url: width: 150 }}"
                       alt="{{ item.title | escape }}"
                       width="150" height="150"
                       loading="lazy">
                {% endif %}
              </a>
            </div>
            
            <div class="cart-item-info">
              <a href="{{ item.url }}" class="cart-item-title">
                {{ item.product.title }}
              </a>
              
              {% unless item.variant.title contains 'Default' %}
                <p class="cart-item-variant">{{ item.variant.title }}</p>
              {% endunless %}
              
              <p class="cart-item-vendor">{{ item.vendor }}</p>
              
              <p class="cart-item-price">
                {{ item.final_line_price | money }}
                {% if item.original_line_price != item.final_line_price %}
                  <s>{{ item.original_line_price | money }}</s>
                {% endif %}
              </p>
            </div>
            
            ''' + qty_section + '''
            
            ''' + remove_section + '''
          </div>
        {% endfor %}
      </div>
      
      <div class="cart-footer">
        
        ''' + notes_section + '''
        
        ''' + discount_section + '''
        
        <div class="cart-totals">
          <div class="cart-subtotal">
            <span class="label">Subtotal</span>
            <span class="value">{{ cart.total_price | money }}</span>
          </div>
          
          {% if cart.total_discounts > 0 %}
            <div class="cart-discount-amount">
              <span class="label">Discount</span>
              <span class="value">-{{ cart.total_discounts | money }}</span>
            </div>
          {% endif %}
          
          <div class="cart-shipping-note">
            Shipping and taxes calculated at checkout
          </div>
        </div>
        
        ''' + checkout_section + '''
      </div>
    </form>
    
  {% else %}
    
    ''' + empty_section + '''
    
  {% endif %}
</div>

<script>
  function updateQty(line, qty) {
    var newQty = typeof qty === 'number' 
      ? parseInt(document.querySelector('[data-line="' + line + '"] input').value) + qty
      : parseInt(qty);
    
    if (newQty < 0) newQty = 0;
    
    fetch('/cart/change.js', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ line: line, quantity: newQty })
    })
    .then(r => r.json())
    .then(cart => {
      if (newQty === 0) {
        document.querySelector('[data-line="' + line + '"]').remove();
      } else {
        document.querySelector('[data-line="' + line + '"] input').value = newQty;
      }
      updateCartTotals(cart);
    });
  }
  
  function updateCartTotals(cart) {
    document.querySelector('.cart-subtotal .value').textContent = formatMoney(cart.total_price);
    if (cart.item_count === 0) {
      location.reload();
    }
  }
  
  function formatMoney(cents) {
    return '$' + (cents / 100).toFixed(2);
  }
</script>
'''
    return template


def generate_404_template():
    """Generate 404.liquid"""
    return '''<!-- 404.liquid - Generated by Shopify Recon -->
<div class="error-404">
  <h1>404</h1>
  <h2>Page Not Found</h2>
  <p>The page you're looking for doesn't exist or has been moved.</p>
  
  <div class="error-actions">
    <a href="/" class="btn btn-home">Back to Home</a>
    <a href="/collections/all" class="btn btn-shop">Browse Products</a>
  </div>
  
  <div class="search-suggestions">
    <h3>Try searching:</h3>
    <form action="/search" method="get">
      <input type="search" name="q" placeholder="Search...">
      <button type="submit">Search</button>
    </form>
  </div>
</div>
'''


def generate_page_template():
    """Generate page.liquid for static pages"""
    return '''<!-- page.liquid - Generated by Shopify Recon -->
<div class="page-content">
  <h1>{{ page.title }}</h1>
  
  <div class="rte">
    {{ page.content }}
  </div>
</div>
'''


def generate_blog_template():
    """Generate blog.liquid for blog listing"""
    return '''<!-- blog.liquid - Generated by Shopify Recon -->
<div class="blog-page">
  <h1>{{ blog.title }}</h1>
  
  {% if blog.articles.size > 0 %}
    <div class="article-list">
      {% for article in blog.articles %}
        <article class="article-card">
          {% if article.image %}
            <a href="{{ article.url }}" class="article-image">
              <img src="{{ article.image | image_url: width: 600 }}"
                   alt="{{ article.title | escape }}"
                   loading="lazy"
                   width="600" height="400">
            </a>
          {% endif %}
          
          <div class="article-info">
            <h2><a href="{{ article.url }}">{{ article.title }}</a></h2>
            <p class="article-date">{{ article.published_at | date: "%B %d, %Y" }}</p>
            <p class="article-excerpt">
              {{ article.excerpt_or_content | strip_html | truncatewords: 40 }}
            </p>
            <a href="{{ article.url }}" class="read-more">Read More </a>
          </div>
        </article>
      {% endfor %}
    </div>
    
    {% if paginate.pages > 1 %}
      <nav class="pagination">
        {% if paginate.previous %}
          <a href="{{ paginate.previous.url }}">&laquo; Previous</a>
        {% endif %}
        {% for part in paginate.parts %}
          {% if part.is_link %}
            <a href="{{ part.url }}">{{ part.title }}</a>
          {% else %}
            <span class="current">{{ part.title }}</span>
          {% endif %}
        {% endfor %}
        {% if paginate.next %}
          <a href="{{ paginate.next.url }}">Next &raquo;</a>
        {% endif %}
      </nav>
    {% endif %}
    
  {% else %}
    <p>No articles found.</p>
  {% endif %}
</div>
'''


def generate_article_template():
    """Generate article.liquid for single blog post"""
    return '''<!-- article.liquid - Generated by Shopify Recon -->
<article class="article-page">
  
  <header class="article-header">
    <h1>{{ article.title }}</h1>
    <p class="article-meta">
      Published on {{ article.published_at | date: "%B %d, %Y" }}
      {% if article.author %} by {{ article.author }}{% endif %}
    </p>
    
    {% if article.image %}
      <img src="{{ article.image | image_url: width: 1200 }}"
           alt="{{ article.title | escape }}"
           class="article-featured-image"
           width="1200">
    {% endif %}
  </header>
  
  <div class="article-content rte">
    {{ article.content }}
  </div>
  
  {% if blog.comments_enabled? %}
    <div class="article-comments">
      <h2>Comments ({{ article.comments_count }})</h2>
      
      {% if article.comments.size > 0 %}
        {% for comment in article.comments %}
          <div class="comment">
            <p class="comment-author">{{ comment.author }}</p>
            <p class="comment-date">{{ comment.created_at | date: "%B %d, %Y" }}</p>
            <div class="comment-body">{{ comment.content }}</div>
          </div>
        {% endfor %}
      {% endif %}
      
      <form action="{{ article.url }}/comments" method="post" class="comment-form">
        <h3>Leave a Comment</h3>
        <input type="text" name="comment[author]" placeholder="Your Name" required>
        <input type="email" name="comment[email]" placeholder="Your Email" required>
        <textarea name="comment[body]" placeholder="Your Comment" required></textarea>
        <button type="submit" class="btn">Post Comment</button>
      </form>
    </div>
  {% endif %}
  
  <nav class="article-nav">
    {% if blog.previous_article %}
      <a href="{{ blog.previous_article }}">&larr; Previous Article</a>
    {% endif %}
    {% if blog.next_article %}
      <a href="{{ blog.next_article }}">Next Article &rarr;</a>
    {% endif %}
  </nav>
</article>
'''


def generate_list_collections_template():
    """Generate list-collections.liquid"""
    return '''<!-- list-collections.liquid - Generated by Shopify Recon -->
<div class="collections-list">
  <h1>Collections</h1>
  
  <div class="collections-grid">
    {% for collection in collections %}
      <div class="collection-card">
        <a href="{{ collection.url }}">
          {% if collection.image %}
            <img src="{{ collection.image | image_url: width: 400 }}"
                 alt="{{ collection.title | escape }}"
                 loading="lazy"
                 width="400" height="300">
          {% endif %}
          <h2>{{ collection.title }}</h2>
          <p>{{ collection.all_products_count }} products</p>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
'''


def generate_customers_templates():
    """Generate customer account templates"""
    return {
        "customers/login.liquid": '''<!-- customers/login.liquid - Generated by Shopify Recon -->
<div class="customer-login">
  <h1>Login</h1>
  
  {% form 'customer_login' %}
    {% if form.errors %}
      <div class="form-errors">{{ form.errors | default_errors }}</div>
    {% endif %}
    
    <input type="email" name="customer[email]" placeholder="Email" required>
    <input type="password" name="customer[password]" placeholder="Password" required>
    
    <button type="submit" class="btn">Login</button>
  {% endform %}
  
  <p><a href="/account/register">Create account</a> | <a href="/account/recover">Forgot password?</a></p>
</div>
''',
        "customers/register.liquid": '''<!-- customers/register.liquid - Generated by Shopify Recon -->
<div class="customer-register">
  <h1>Create Account</h1>
  
  {% form 'create_customer' %}
    {% if form.errors %}
      <div class="form-errors">{{ form.errors | default_errors }}</div>
    {% endif %}
    
    <input type="text" name="customer[first_name]" placeholder="First Name">
    <input type="text" name="customer[last_name]" placeholder="Last Name">
    <input type="email" name="customer[email]" placeholder="Email" required>
    <input type="password" name="customer[password]" placeholder="Password" required>
    
    <button type="submit" class="btn">Create Account</button>
  {% endform %}
  
  <p>Already have an account? <a href="/account/login">Login</a></p>
</div>
''',
        "customers/account.liquid": '''<!-- customers/account.liquid - Generated by Shopify Recon -->
<div class="customer-account">
  <h1>My Account</h1>
  
  <div class="account-info">
    <h2>Account Details</h2>
    <p>{{ customer.name }}</p>
    <p>{{ customer.email }}</p>
    <p>{{ customer.default_address }}</p>
    <a href="/account/addresses">Manage Addresses</a>
  </div>
  
  <div class="order-history">
    <h2>Order History</h2>
    {% if customer.orders.size > 0 %}
      <table class="orders-table">
        <thead>
          <tr><th>Order</th><th>Date</th><th>Status</th><th>Total</th></tr>
        </thead>
        <tbody>
          {% for order in customer.orders %}
            <tr>
              <td><a href="{{ order.customer_url }}">{{ order.name }}</a></td>
              <td>{{ order.created_at | date: "%b %d, %Y" }}</td>
              <td>{{ order.fulfillment_status_label }}</td>
              <td>{{ order.total_price | money }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No orders yet.</p>
    {% endif %}
  </div>
  
  <a href="/account/logout" class="btn">Logout</a>
</div>
''',
    }


def generate_snippets():
    """Generate essential snippet files"""
    return {
        "product-card.liquid": '''<!-- snippets/product-card.liquid - Generated by Shopify Recon -->
<div class="product-card">
  <a href="{{ product.url }}" class="product-card-link">
    <div class="product-card-image">
      {% if product.featured_image %}
        <img src="{{ product.featured_image | image_url: width: 400 }}"
             alt="{{ product.title | escape }}"
             loading="lazy"
             width="400" height="400">
      {% else %}
        {{ 'product-1' | placeholder_svg_tag: 'product-placeholder' }}
      {% endif %}
      
      {% if product.compare_at_price > product.price %}
        <span class="product-badge sale">Sale</span>
      {% endif %}
      
      {% unless product.available %}
        <span class="product-badge sold-out">Sold Out</span>
      {% endunless %}
    </div>
    
    <div class="product-card-info">
      <h3 class="product-card-title">{{ product.title }}</h3>
      
      {% if product.vendor %}
        <p class="product-card-vendor">{{ product.vendor }}</p>
      {% endif %}
      
      <p class="product-card-price">
        {{ product.price | money }}
        {% if product.compare_at_price > product.price %}
          <s>{{ product.compare_at_price | money }}</s>
        {% endif %}
      </p>
      
      {% if product.variants.size > 1 %}
        <p class="product-card-variants">
          {{ product.variants.size }} options
        </p>
      {% endif %}
    </div>
  </a>
  
  <form action="/cart/add" method="post" class="product-card-form">
    <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}">
    <button type="submit" name="add" 
            class="btn btn-quick-add"
            {% unless product.available %}disabled{% endunless %}>
      {% if product.available %}Quick Add{% else %}Sold Out{% endif %}
    </button>
  </form>
</div>
''',
        "pagination.liquid": '''<!-- snippets/pagination.liquid - Generated by Shopify Recon -->
{% if paginate.pages > 1 %}
  <nav class="pagination" aria-label="Pagination">
    {% if paginate.previous %}
      <a href="{{ paginate.previous.url }}" class="pagination-prev" aria-label="Previous">
        &laquo;
      </a>
    {% endif %}
    
    {% for part in paginate.parts %}
      {% if part.is_link %}
        <a href="{{ part.url }}" class="pagination-link">{{ part.title }}</a>
      {% else %}
        {% if part.title == paginate.current_page %}
          <span class="pagination-current" aria-current="page">{{ part.title }}</span>
        {% else %}
          <span class="pagination-gap">{{ part.title }}</span>
        {% endif %}
      {% endif %}
    {% endfor %}
    
    {% if paginate.next %}
      <a href="{{ paginate.next.url }}" class="pagination-next" aria-label="Next">
        &raquo;
      </a>
    {% endif %}
  </nav>
{% endif %}
''',
        "breadcrumbs.liquid": '''<!-- snippets/breadcrumbs.liquid - Generated by Shopify Recon -->
<nav class="breadcrumbs" aria-label="Breadcrumb">
  <ol>
    <li><a href="/">Home</a></li>
    
    {% if collection %}
      <li aria-hidden="true">/</li>
      <li><a href="{{ collection.url }}">{{ collection.title }}</a></li>
    {% endif %}
    
    {% if product %}
      <li aria-hidden="true">/</li>
      <li aria-current="page">{{ product.title }}</li>
    {% elsif page %}
      <li aria-hidden="true">/</li>
      <li aria-current="page">{{ page.title }}</li>
    {% elsif blog %}
      <li aria-hidden="true">/</li>
      <li><a href="{{ blog.url }}">{{ blog.title }}</a></li>
    {% elsif article %}
      <li aria-hidden="true">/</li>
      <li aria-current="page">{{ article.title }}</li>
    {% endif %}
  </ol>
</nav>
''',
        "header-nav.liquid": '''<!-- snippets/header-nav.liquid - Generated by Shopify Recon -->
<nav class="header-nav" aria-label="Main navigation">
  <ul class="nav-list">
    {% for link in linklists.main-menu.links %}
      <li class="nav-item">
        <a href="{{ link.url }}" class="nav-link">{{ link.title }}</a>
        
        {% if link.links.size > 0 %}
          <ul class="nav-dropdown">
            {% for child in link.links %}
              <li><a href="{{ child.url }}">{{ child.title }}</a></li>
            {% endfor %}
          </ul>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</nav>

<div class="header-actions">
  <form action="/search" method="get" class="header-search">
    <input type="search" name="q" placeholder="Search..." aria-label="Search">
    <button type="submit" aria-label="Search"></button>
  </form>
  
  <a href="/account" class="header-account" aria-label="Account"></a>
  
  <a href="/cart" class="header-cart" aria-label="Cart">
    <span class="cart-count">{{ cart.item_count }}</span>
  </a>
</div>
''',
        "footer.liquid": '''<!-- snippets/footer.liquid - Generated by Shopify Recon -->
<footer class="site-footer">
  <div class="footer-columns">
    
    <div class="footer-col">
      <h4>{{ shop.name }}</h4>
      <p>{{ shop.description }}</p>
    </div>
    
    <div class="footer-col">
      <h4>Shop</h4>
      <ul>
        {% for link in linklists.footer.links %}
          <li><a href="{{ link.url }}">{{ link.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
    
    <div class="footer-col">
      <h4>Help</h4>
      <ul>
        <li><a href="/pages/contact">Contact Us</a></li>
        <li><a href="/pages/shipping">Shipping</a></li>
        <li><a href="/pages/returns">Returns</a></li>
        <li><a href="/pages/faq">FAQ</a></li>
      </ul>
    </div>
    
    <div class="footer-col">
      <h4>Newsletter</h4>
      <form action="/contact#ContactFooter" method="post" class="newsletter-form">
        <input type="email" name="contact[email]" placeholder="Your email">
        <button type="submit">Subscribe</button>
      </form>
      
      <div class="social-links">
        {% if settings.social_facebook %}<a href="{{ settings.social_facebook }}">Facebook</a>{% endif %}
        {% if settings.social_instagram %}<a href="{{ settings.social_instagram }}">Instagram</a>{% endif %}
        {% if settings.social_twitter %}<a href="{{ settings.social_twitter }}">Twitter</a>{% endif %}
        {% if settings.social_youtube %}<a href="{{ settings.social_youtube }}">YouTube</a>{% endif %}
      </div>
    </div>
    
  </div>
  
  <div class="footer-bottom">
    <p>&copy; {{ 'now' | date: "%Y" }} {{ shop.name }}. All rights reserved.</p>
    <div class="payment-icons">
      {% for type in shop.enabled_payment_types %}
        {{ type | payment_type_svg_tag: class: 'payment-icon' }}
      {% endfor %}
    </div>
  </div>
</footer>
''',
    }


def generate_layout(page_data):
    """Generate theme.liquid layout"""
    return '''<!-- layout/theme.liquid - Generated by Shopify Recon -->
<!DOCTYPE html>
<html lang="{{ shop.locale }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
  <title>{{ page_title }}{% if current_tags %} - tagged "{{ current_tags | join: ', ' }}"{% endif %}{% if current_page != 1 %} - Page {{ current_page }}{% endif %}{% unless page_title contains shop.name %} - {{ shop.name }}{% endunless %}</title>
  
  {% if page_description %}
    <meta name="description" content="{{ page_description | escape }}">
  {% endif %}
  
  <link rel="canonical" href="{{ canonical_url }}">
  
  {% if settings.favicon %}
    <link rel="icon" href="{{ settings.favicon | image_url: width: 32 }}" sizes="32x32">
  {% endif %}
  
  {{ content_for_header }}
  
  <link rel="stylesheet" href="{{ 'theme.css' | asset_url }}">
  
  <meta property="og:site_name" content="{{ shop.name }}">
  <meta property="og:url" content="{{ canonical_url }}">
  <meta property="og:title" content="{{ page_title }}">
  <meta property="og:type" content="website">
  {% if page_description %}
    <meta property="og:description" content="{{ page_description | escape }}">
  {% endif %}
  {% if product.featured_image %}
    <meta property="og:image" content="{{ product.featured_image | image_url: width: 1200 }}">
  {% endif %}
  
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ page_title }}">
  {% if page_description %}
    <meta name="twitter:description" content="{{ page_description | escape }}">
  {% endif %}
</head>
<body class="template-{{ template.name }}">
  
  <a href="#MainContent" class="skip-link">Skip to content</a>
  
  <header class="site-header">
    <div class="header-inner">
      <a href="/" class="logo">{{ shop.name }}</a>
      {% render 'header-nav' %}
    </div>
  </header>
  
  {% render 'breadcrumbs' %}
  
  <main id="MainContent" role="main">
    {{ content_for_layout }}
  </main>
  
  {% render 'footer' %}
  
  <script src="{{ 'theme.js' | asset_url }}" defer></script>
</body>
</html>
'''


def main():
    if len(sys.argv) < 3:
        print("FULL TEMPLATE GENERATOR")
        print("━" * 69)
        print()
        print("Usage: python3 template-generator.py <page-analysis.json> <output-dir>")
        print("Example: python3 template-generator.py ./page-analysis.json ./my-theme")
        sys.exit(1)
    
    analysis_path = sys.argv[1]
    output_dir = sys.argv[2]
    
    print("FULL TEMPLATE GENERATOR")
    print("━" * 69)
    print(f"  Input: {analysis_path}")
    print(f"  Output: {output_dir}")
    print()
    
    analysis = load_analysis(analysis_path)
    pages = analysis.get("pages", {})
    
    # Create directory structure
    dirs = ["templates", "templates/customers", "snippets", "layout", "sections", "assets", "config"]
    for d in dirs:
        os.makedirs(os.path.join(output_dir, d), exist_ok=True)
    
    generated = []
    
    # Layout
    print("  [1/4] Generating layout...")
    layout_path = os.path.join(output_dir, "layout", "theme.liquid")
    with open(layout_path, "w") as f:
        f.write(generate_layout(pages))
    generated.append("layout/theme.liquid")
    
    # Templates
    print("  [2/4] Generating templates...")
    templates = {
        "product.liquid": generate_product_template(pages.get("product", {})),
        "collection.liquid": generate_collection_template(pages.get("collection", {})),
        "search.liquid": generate_search_template(pages.get("search", {})),
        "cart.liquid": generate_cart_template(pages.get("cart", {})),
        "404.liquid": generate_404_template(),
        "page.liquid": generate_page_template(),
        "blog.liquid": generate_blog_template(),
        "article.liquid": generate_article_template(),
        "list-collections.liquid": generate_list_collections_template(),
    }
    
    for name, content in templates.items():
        path = os.path.join(output_dir, "templates", name)
        with open(path, "w") as f:
            f.write(content)
        generated.append(f"templates/{name}")
    
    # Customer templates
    print("  [3/4] Generating customer templates...")
    customer_templates = generate_customers_templates()
    for name, content in customer_templates.items():
        path = os.path.join(output_dir, "templates", name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        generated.append(f"templates/{name}")
    
    # Snippets
    print("  [4/4] Generating snippets...")
    snippets = generate_snippets()
    for name, content in snippets.items():
        path = os.path.join(output_dir, "snippets", name)
        with open(path, "w") as f:
            f.write(content)
        generated.append(f"snippets/{name}")
    
    # Summary
    print(f"\nTEMPLATE GENERATION COMPLETE")
    print(f"━" * 69)
    print(f"  Output: {output_dir}/")
    print(f"  {len(generated)} files generated")
    print()
    print("Theme Structure:")
    for f in generated:
        print(f"  • {f}")
    
    print(f"\nDeploy:")
    print(f"  shopify theme dev --store=YOUR_STORE.myshopify.com --path={output_dir}")
    print(f"  shopify theme push --store=YOUR_STORE.myshopify.com --path={output_dir}")


if __name__ == "__main__":
    main()
