#!/usr/bin/env python3
"""
Variant Selector + Filter Cloner
Clones Shopify variant picker logic + collection filter logic from rendered HTML.
"""
import re, sys, json
from pathlib import Path
from bs4 import BeautifulSoup

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 variant-filter-cloner.py <extracted_dir>")
        sys.exit(1)
    
    extracted_dir = Path(sys.argv[1])
    print("=" * 60)
    print("Variant Selector + Filter Cloner")
    print("=" * 60)
    
    # Load product page
    product_html_path = extracted_dir / "pages" / "product.html"
    collection_html_path = extracted_dir / "pages" / "collection.html"
    products_json_path = extracted_dir / "extracted" / "api" / "products.json"
    
    # === VARIANT SELECTOR ===
    print("\n--- Variant Selector ---")
    product_soup = None
    if product_html_path.exists():
        product_soup = BeautifulSoup(product_html_path.read_text(encoding='utf-8', errors='replace'), 'lxml')
    
    # Detect variant picker type
    picker_type = "dropdown"  # default
    if product_soup:
        if product_soup.find('select', attrs={'name': re.compile(r'id|variant', re.I)}):
            picker_type = "dropdown"
        elif product_soup.find(class_=re.compile(r'variant.*radio|swatch|option.*button', re.I)):
            picker_type = "swatch"
        elif product_soup.find('input', attrs={'type': 'radio', 'name': re.compile(r'option|variant', re.I)}):
            picker_type = "radio"
    
    print(f"Picker type detected: {picker_type}")
    
    # Load product data for variant structure
    variants_example = []
    if products_json_path.exists():
        data = json.load(open(products_json_path))
        products = data.get('products', data) if isinstance(data, dict) else data
        if products and isinstance(products, list):
            first = products[0]
            variants_example = first.get('variants', [])
            print(f"Example product: {first.get('title', 'N/A')}")
            print(f"Variants: {len(variants_example)}")
            if variants_example:
                v = variants_example[0]
                v_title = v.get('title', 'N/A')
                v_price = v.get('price', 0)
                try:
                    v_price_float = float(v_price) / 100
                except (TypeError, ValueError):
                    v_price_float = 0
                print(f"  Example: {v_title} - ${v_price_float:.2f}")
    
    # Generate main-product.liquid
    sections_dir = extracted_dir / "theme" / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)
    
    product_section = """{%- comment -%}
  Main Product Section - Auto-generated by variant-selector-cloner
  Variant picker type: """ + picker_type + """
{%- endcomment -%}

<section class="product-section" data-section-type="product">
  <div class="product-container">
    <div class="product__media">
      {%- for media in product.media -%}
        <div class="product__media-item" data-media-id="{{ media.id }}">
          {%- if media.media_type == 'image' -%}
            <img src="{{ media | image_url: width: 1000 }}"
                 alt="{{ media.alt | escape }}"
                 loading="{% if forloop.first %}eager{% else %}lazy{% endif %}"
                 width="1000" height="1000">
          {%- elsif media.media_type == 'video' -%}
            {{ media | media_tag: image_size: '1000x' }}
          {%- endif -%}
        </div>
      {%- else -%}
        {{ 'product-1' | placeholder_svg_tag: 'product__placeholder' }}
      {%- endfor -%}
    </div>

    <div class="product__info">
      <h1 class="product__title">{{ product.title }}</h1>

      {%- if product.vendor != blank -%}
        <p class="product__vendor">{{ product.vendor }}</p>
      {%- endif -%}

      <div class="product__price" data-price-container>
        <span class="product__price--current" data-price>
          {{ product.price | money }}
        </span>
        {%- if product.compare_at_price > product.price -%}
          <span class="product__price--compare" data-compare-price>
            {{ product.compare_at_price | money }}
          </span>
          <span class="product__badge--sale">Sale</span>
        {%- endif -%}
      </div>

      <div class="product__description">
        {{ product.description }}
      </div>

      {%- form 'product', product, data-product-form: '', data-product-id: product.id -%}
        <input type="hidden" name="id" value="{{ product.selected_or_first_available_variant.id }}" data-variant-id>

        {%- unless product.has_only_default_variant -%}
          <div class="product__options" data-variant-picker>
            {%- for option in product.options_with_values -%}
              <fieldset class="product__option" data-option-index="{{ forloop.index0 }}">
                <legend class="product__option-label">
                  {{ option.name }}: <span data-option-value>{{ option.selected_value }}</span>
                </legend>
                <div class="product__option-values">
                  {%- for value in option.values -%}
                    <label class="product__option-value {% if option.selected_value == value %}is-selected{% endif %}">
                      <input type="radio"
                             name="option{{ option.position }}"
                             value="{{ value | escape }}"
                             {% if option.selected_value == value %}checked{% endif %}
                             data-variant-input
                             data-option-position="{{ option.position }}">
                      <span class="product__option-value-label">{{ value }}</span>
                    </label>
                  {%- endfor -%}
                </div>
              </fieldset>
            {%- endfor -%}
          </div>
        {%- endunless -%}

        <div class="product__quantity">
          <label for="Quantity">{{ 'products.product.quantity' | t }}</label>
          <input type="number" id="Quantity" name="quantity" value="1" min="1" data-quantity-input>
        </div>

        <div class="product__buttons">
          <button type="submit" name="add" class="btn btn--add-to-cart" data-add-to-cart
                  {% unless product.available %}disabled{% endunless %}>
            <span data-add-to-cart-text>
              {%- if product.available -%}
                {{ 'products.product.add_to_cart' | t }}
              {%- else -%}
                {{ 'products.product.sold_out' | t }}
              {%- endif -%}
            </span>
          </button>
        </div>

        {{ form | payment_button }}
      {%- endform -%}

      {%- if product.metafields.reviews.rating.value -%}
        <div class="product__reviews">
          {% render 'product-reviews', product: product %}
        </div>
      {%- endif -%}
    </div>
  </div>
</section>

<script type="application/json" data-product-json>
  {{ product | json }}
</script>

<script>
  (function() {
    const productData = JSON.parse(
      document.querySelector('[data-product-json]').textContent
    );
    const form = document.querySelector('[data-product-form]');
    const variantInput = form.querySelector('[data-variant-id]');
    const optionInputs = form.querySelectorAll('[data-variant-input]');
    const priceEl = document.querySelector('[data-price]');
    const compareEl = document.querySelector('[data-compare-price]');
    const addBtn = form.querySelector('[data-add-to-cart]');
    const addText = form.querySelector('[data-add-to-cart-text]');

    function getSelectedOptions() {
      const options = [];
      const groups = {};
      optionInputs.forEach(input => {
        if (input.checked) {
          groups[input.dataset.optionPosition] = input.value;
        }
      });
      for (let i = 1; i <= Object.keys(groups).length + 1; i++) {
        if (groups[i]) options.push(groups[i]);
      }
      return options;
    }

    function findVariant(options) {
      return productData.variants.find(v => {
        return v.options.every((opt, i) => opt === options[i]);
      });
    }

    function updateVariant() {
      const options = getSelectedOptions();
      const variant = findVariant(options);
      
      if (!variant) return;

      variantInput.value = variant.id;

      // Update price
      priceEl.textContent = Shopify.formatMoney(variant.price, {{ cart.currency.symbol | json }});

      if (variant.compare_at_price > variant.price) {
        compareEl.textContent = Shopify.formatMoney(variant.compare_at_price);
        compareEl.style.display = '';
      } else {
        compareEl.style.display = 'none';
      }

      // Update availability
      if (variant.available) {
        addBtn.disabled = false;
        addText.textContent = {{ 'products.product.add_to_cart' | t | json }};
      } else {
        addBtn.disabled = true;
        addText.textContent = {{ 'products.product.sold_out' | t | json }};
      }

      // Update URL
      const url = new URL(window.location);
      url.searchParams.set('variant', variant.id);
      window.history.replaceState({}, '', url);

      // Update image
      if (variant.featured_image) {
        const media = document.querySelector(`[data-media-id="${variant.featured_media_id}"]`);
        if (media) media.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
      }
    }

    optionInputs.forEach(input => {
      input.addEventListener('change', updateVariant);
    });

    // Quantity selector
    const qtyInput = form.querySelector('[data-quantity-input]');
    const qtyMinus = form.querySelector('[data-quantity-minus]');
    const qtyPlus = form.querySelector('[data-quantity-plus]');

    if (qtyMinus) qtyMinus.addEventListener('click', () => {
      qtyInput.value = Math.max(1, parseInt(qtyInput.value) - 1);
    });
    if (qtyPlus) qtyPlus.addEventListener('click', () => {
      qtyInput.value = parseInt(qtyInput.value) + 1;
    });
  })();
</script>
"""
    
    product_path = sections_dir / "main-product.liquid"
    product_path.write_text(product_section, encoding='utf-8')
    print(f"{product_path} ({product_path.stat().st_size:,} bytes)")
    
    # === FILTER CLONER ===
    print("\n--- Filter Cloner ---")
    
    # Detect filter type
    filter_type = "sidebar"
    if collection_html_path.exists():
        col_soup = BeautifulSoup(collection_html_path.read_text(encoding='utf-8', errors='replace'), 'lxml')
        if col_soup.find(class_=re.compile(r'filter.*sidebar|facets|filter.*left', re.I)):
            filter_type = "sidebar"
        elif col_soup.find(class_=re.compile(r'filter.*top|filter.*bar|filter.*horizontal', re.I)):
            filter_type = "topbar"
        elif col_soup.find(class_=re.compile(r'filter.*drawer|filter.*modal', re.I)):
            filter_type = "drawer"
        
        # Detect sort
        sort_select = col_soup.find('select', attrs={'name': re.compile(r'sort', re.I)})
        has_sort = bool(sort_select)
        print(f"Sort dropdown detected: {has_sort}")
    
    print(f"Filter type detected: {filter_type}")
    
    collection_section = """{%- comment -%}
  Main Collection Section - Auto-generated by filter-cloner
  Filter type: """ + filter_type + """
{%- endcomment -%}

<section class="collection-section" data-section-type="collection">
  <div class="collection__header">
    <h1>{{ collection.title }}</h1>
    {%- if collection.description != blank -%}
      <div class="collection__description">{{ collection.description }}</div>
    {%- endif -%}
  </div>

  <div class="collection__layout">
    <aside class="collection__filters" data-filters>
      <form data-filter-form>
        {%- for filter in collection.filters -%}
          <div class="filter-group" data-filter-group>
            <button type="button" class="filter-group__toggle" aria-expanded="true">
              {{ filter.label }}
            </button>
            <div class="filter-group__content">
              {%- case filter.type -%}
                {%- when 'price_range' -%}
                  <div class="filter-price">
                    <input type="number"
                           name="{{ filter.min_value.param_name }}"
                           value="{{ filter.min_value.value }}"
                           min="0"
                           max="{{ filter.range_max | money_without_currency | replace: ',', '' }}"
                           placeholder="Min"
                           data-filter-input>
                    <span>&mdash;</span>
                    <input type="number"
                           name="{{ filter.max_value.param_name }}"
                           value="{{ filter.max_value.value }}"
                           min="0"
                           max="{{ filter.range_max | money_without_currency | replace: ',', '' }}"
                           placeholder="Max"
                           data-filter-input>
                  </div>

                {%- when 'list' or 'boolean' -%}
                  {%- for value in filter.values -%}
                    <label class="filter-option {% if value.active %}is-active{% endif %} {% if value.count == 0 and value.active == false %}is-disabled{% endif %}">
                      <input type="checkbox"
                             name="{{ value.param_name }}"
                             value="{{ value.value }}"
                             {% if value.active %}checked{% endif %}
                             data-filter-input>
                      <span>{{ value.label }}</span>
                      <span class="filter-option__count">({{ value.count }})</span>
                    </label>
                  {%- endfor -%}
              {%- endcase -%}
            </div>
          </div>
        {%- endfor -%}

        {%- if collection.filters.size > 0 -%}
          <button type="button" class="btn btn--clear" data-clear-filters>
            {{ 'collections.sorting.clear_all' | t }}
          </button>
        {%- endif -%}
      </form>
    </aside>

    <div class="collection__products">
      <div class="collection__toolbar">
        <div class="collection__count">
          {{ 'collections.general.items_count' | t: count: collection.products_count }}
        </div>

        <div class="collection__sort">
          <label for="SortBy">{{ 'collections.sorting.title' | t }}</label>
          <select id="SortBy" data-sort-select>
            {%- for option in collection.sort_options -%}
              <option value="{{ option.value }}" {% if option.value == collection.sort_by %}selected{% endif %}>
                {{ option.name }}
              </option>
            {%- endfor -%}
          </select>
        </div>
      </div>

      <div class="product-grid" data-product-grid
           style="grid-template-columns: repeat({{ settings.product_grid_columns }}, 1fr); gap: {{ settings.grid_gap }}px;">
        {%- for product in collection.products -%}
          {% render 'product-card', product_card_product: product %}
        {%- else -%}
          <p class="collection__empty">{{ 'collections.general.no_matches' | t }}</p>
        {%- endfor -%}
      </div>

      {%- render 'pagination', paginate: paginate -%}
    </div>
  </div>
</section>

<script>
  (function() {
    const form = document.querySelector('[data-filter-form]');
    const sortSelect = document.querySelector('[data-sort-select]');
    const grid = document.querySelector('[data-product-grid]');

    // AJAX filter update
    function updateResults(url) {
      fetch(url)
        .then(r => r.text())
        .then(html => {
          const parser = new DOMParser();
          const doc = parser.parseFromString(html, 'text/html');
          const newGrid = doc.querySelector('[data-product-grid]');
          const newFilters = doc.querySelector('[data-filters]');
          
          if (newGrid) grid.innerHTML = newGrid.innerHTML;
          if (newFilters) document.querySelector('[data-filters]').innerHTML = newFilters.innerHTML;
          
          // Update URL
          window.history.pushState({}, '', url);
        })
        .catch(err => console.error('Filter update failed:', err));
    }

    // Filter inputs
    form.addEventListener('change', function(e) {
      if (e.target.matches('[data-filter-input]')) {
        const params = new URLSearchParams(new FormData(form));
        const url = new URL(window.location);
        
        // Preserve sort
        if (sortSelect.value) url.searchParams.set('sort_by', sortSelect.value);
        
        // Clear existing filter params
        const keysToDelete = [];
        url.searchParams.forEach((v, k) => {
          if (k.startsWith('filter.') || k.startsWith('filter.v.')) keysToDelete.push(k);
        });
        keysToDelete.forEach(k => url.searchParams.delete(k));
        
        // Add new filter params
        params.forEach((v, k) => {
          if (v) url.searchParams.append(k, v);
        });
        
        updateResults(url.toString());
      }
    });

    // Sort
    sortSelect.addEventListener('change', function() {
      const url = new URL(window.location);
      url.searchParams.set('sort_by', this.value);
      updateResults(url.toString());
    });

    // Clear all
    const clearBtn = document.querySelector('[data-clear-filters]');
    if (clearBtn) {
      clearBtn.addEventListener('click', function() {
        const url = new URL(window.location.pathname, window.location.origin);
        if (sortSelect.value) url.searchParams.set('sort_by', sortSelect.value);
        updateResults(url.toString());
      });
    }
  })();
</script>
"""
    
    collection_path = sections_dir / "main-collection.liquid"
    collection_path.write_text(collection_section, encoding='utf-8')
    print(f"{collection_path} ({collection_path.stat().st_size:,} bytes)")
    
    print(f"\n{'='*60}")
    print("Variant Selector + Filter Cloner Complete!")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
